import { Blueprint } from '@/types/blueprint';
import { allTechnologies } from '@/data/options/technologies';
import { featureOptions } from '@/data/options/features';
import { integrationOptions } from '@/data/options/integrations';
import { qualityOptions } from '@/data/options/quality';

// ─── Helpers ─────────────────────────────────────────────────────────

function fmt(val: string | null): string {
  if (!val) return 'N/A';
  return val.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

function lookupName(id: string): string {
  const opt =
    allTechnologies.find((o) => o.id === id) ??
    featureOptions.find((o) => o.id === id) ??
    integrationOptions.find((o) => o.id === id) ??
    Object.values(qualityOptions).flat().find((o) => o.id === id);
  return opt?.name ?? fmt(id);
}

function techByCategory(bp: Blueprint): [string, string[]][] {
  return Object.entries(bp.technology)
    .filter(([, ids]) => ids && Array.isArray(ids) && ids.length > 0)
    .map(([cat, ids]) => [fmt(cat), ids.map(lookupName).filter(Boolean)] as [string, string[]])
    .filter(([, names]) => names.length > 0);
}

function qualityByCategory(bp: Blueprint): [string, string[]][] {
  return Object.entries(bp.quality)
    .filter(([, ids]) => ids.length > 0)
    .map(([cat, ids]) => [fmt(cat), ids.map(lookupName)]);
}

function today(): string {
  return new Date().toISOString().split('T')[0];
}

// ─── Document Metadata ──────────────────────────────────────────────

export interface GeneratedDocument {
  id: string;
  title: string;
  icon: string;
  description: string;
  content: string;
}

export interface DocumentType {
  id: string;
  title: string;
  icon: string;
  description: string;
  generate: (bp: Blueprint) => string;
}

// ─── Generators ──────────────────────────────────────────────────────

function generatePRD(bp: Blueprint): string {
  const lines: string[] = [];
  const name = bp.basics.name || 'Untitled Project';
  lines.push(`# Product Requirements Document (PRD)`);
  lines.push(`## ${name}`);
  lines.push('');
  lines.push(`**Date:** ${today()}`);
  lines.push(`**Status:** ${bp.status === 'complete' ? 'Final' : 'Draft'}`);
  lines.push('');

  // Overview
  lines.push('## 1. Overview');
  lines.push('');
  lines.push(`**Project Name:** ${name}`);
  lines.push(`**Project Type:** ${fmt(bp.basics.projectType)}`);
  lines.push(`**Industry:** ${bp.basics.industry || 'Not specified'}`);
  lines.push(`**Target Audience:** ${bp.basics.targetAudience || 'Not specified'}`);
  lines.push(`**Business Model:** ${fmt(bp.basics.businessModel)}`);
  lines.push('');
  if (bp.basics.description) {
    lines.push('### Description');
    lines.push('');
    lines.push(bp.basics.description);
    lines.push('');
  }

  // Platforms
  lines.push('## 2. Target Platforms');
  lines.push('');
  if (bp.basics.targetPlatforms.length > 0) {
    for (const p of bp.basics.targetPlatforms) {
      lines.push(`- ${fmt(p)}`);
    }
  } else {
    lines.push('_No platforms selected._');
  }
  lines.push('');

  // Technology Stack
  lines.push('## 3. Technology Stack');
  lines.push('');
  const tech = techByCategory(bp);
  if (tech.length > 0) {
    lines.push('| Layer | Technologies |');
    lines.push('|-------|-------------|');
    for (const [cat, names] of tech) {
      lines.push(`| **${cat}** | ${names.join(', ')} |`);
    }
  } else {
    lines.push('_No technologies selected._');
  }
  lines.push('');

  // Features
  lines.push('## 4. Features');
  lines.push('');
  if (bp.features.selected.length > 0) {
    for (const id of bp.features.selected) {
      const opt = featureOptions.find((o) => o.id === id);
      lines.push(`### ${opt?.icon ?? '•'} ${lookupName(id)}`);
      if (opt?.description) lines.push(`${opt.description}`);
      lines.push('');
    }
  } else {
    lines.push('_No features selected._');
    lines.push('');
  }

  // Integrations
  lines.push('## 5. Integrations');
  lines.push('');
  if (bp.integrations.selected.length > 0) {
    for (const id of bp.integrations.selected) {
      const opt = integrationOptions.find((o) => o.id === id);
      lines.push(`- **${lookupName(id)}** — ${opt?.description ?? ''}`);
    }
  } else {
    lines.push('_No integrations selected._');
  }
  lines.push('');

  // Quality
  lines.push('## 6. Quality & Non-Functional Requirements');
  lines.push('');
  const qual = qualityByCategory(bp);
  if (qual.length > 0) {
    for (const [cat, names] of qual) {
      lines.push(`### ${cat}`);
      for (const n of names) lines.push(`- ${n}`);
      lines.push('');
    }
  } else {
    lines.push('_No quality configurations set._');
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Generated by Blueprint Builder on ${today()}*`);
  return lines.join('\n');
}

function generateREADME(bp: Blueprint): string {
  const name = bp.basics.name || 'Project';
  const lines: string[] = [];
  lines.push(`# ${name}`);
  lines.push('');
  if (bp.basics.description) {
    lines.push(`> ${bp.basics.description}`);
    lines.push('');
  }

  // Badges
  lines.push(`![Type](https://img.shields.io/badge/type-${encodeURIComponent(fmt(bp.basics.projectType))}-6366f1)`);
  lines.push(`![Status](https://img.shields.io/badge/status-${bp.status}-10b981)`);
  lines.push('');

  lines.push('## Tech Stack');
  lines.push('');
  const tech = techByCategory(bp);
  for (const [cat, names] of tech) {
    lines.push(`- **${cat}:** ${names.join(', ')}`);
  }
  lines.push('');

  lines.push('## Features');
  lines.push('');
  for (const id of bp.features.selected) {
    lines.push(`- ${lookupName(id)}`);
  }
  if (bp.features.selected.length === 0) lines.push('_None selected._');
  lines.push('');

  if (bp.integrations.selected.length > 0) {
    lines.push('## Integrations');
    lines.push('');
    for (const id of bp.integrations.selected) {
      lines.push(`- ${lookupName(id)}`);
    }
    lines.push('');
  }

  lines.push('## Getting Started');
  lines.push('');
  lines.push('```bash');
  lines.push('# Install dependencies');
  lines.push('npm install');
  lines.push('');
  lines.push('# Start development server');
  lines.push('npm run dev');
  lines.push('```');
  lines.push('');

  lines.push('## License');
  lines.push('');
  lines.push('MIT');
  lines.push('');
  lines.push(`---`);
  lines.push(`*Generated by Blueprint Builder on ${today()}*`);
  return lines.join('\n');
}

function generateAPISpec(bp: Blueprint): string {
  const name = bp.basics.name || 'Project';
  const lines: string[] = [];
  lines.push(`# API Specification — ${name}`);
  lines.push('');
  lines.push(`**Base URL:** \`https://api.${name.toLowerCase().replace(/[^a-z0-9]/g, '')}.com/v1\``);
  lines.push('');

  // Auth endpoints
  if (bp.features.selected.includes('authentication')) {
    lines.push('## Authentication');
    lines.push('');
    lines.push('### POST /auth/register');
    lines.push('Create a new user account.');
    lines.push('```json');
    lines.push('{ "email": "string", "password": "string", "name": "string" }');
    lines.push('```');
    lines.push('');
    lines.push('### POST /auth/login');
    lines.push('Authenticate and receive a token.');
    lines.push('```json');
    lines.push('{ "email": "string", "password": "string" }');
    lines.push('```');
    lines.push('');
    lines.push('### POST /auth/logout');
    lines.push('Invalidate the current session.');
    lines.push('');
  }

  // Feature-based endpoints
  for (const id of bp.features.selected) {
    if (id === 'authentication') continue;
    const resource = id.replace(/-/g, '_');
    lines.push(`## ${lookupName(id)}`);
    lines.push('');
    
    if (id === 'dashboard') {
      lines.push(`### GET /dashboard/metrics`);
      lines.push(`Retrieve aggregated metrics for the dashboard view.`);
      lines.push('');
      lines.push(`### GET /dashboard/activity`);
      lines.push(`Get recent activity feed for the dashboard.`);
      lines.push('');
    } else if (id === 'user-profiles') {
      lines.push(`### GET /users/:id/profile`);
      lines.push(`Get a specific user's public profile data.`);
      lines.push('');
      lines.push(`### PUT /users/me/profile`);
      lines.push(`Update the authenticated user's profile.`);
      lines.push('');
    } else if (id === 'payments') {
      lines.push(`### POST /payments/checkout`);
      lines.push(`Create a new checkout session.`);
      lines.push('');
      lines.push(`### GET /payments/subscriptions`);
      lines.push(`List active subscriptions for the user.`);
      lines.push('');
    } else if (id === 'messaging') {
      lines.push(`### GET /conversations`);
      lines.push(`List all active conversations for the user.`);
      lines.push('');
      lines.push(`### POST /conversations/:id/messages`);
      lines.push(`Send a new message in a conversation.`);
      lines.push('');
    } else if (id === 'file-uploads') {
      lines.push(`### POST /uploads/presigned-url`);
      lines.push(`Get a pre-signed URL for direct cloud upload.`);
      lines.push('');
    } else if (id === 'search') {
      lines.push(`### GET /search`);
      lines.push(`Perform a full-text search query across resources.`);
      lines.push('');
    } else {
      lines.push(`### GET /${resource}`);
      lines.push(`List all ${lookupName(id).toLowerCase()} items.`);
      lines.push('');
      lines.push(`### POST /${resource}`);
      lines.push(`Create a new ${lookupName(id).toLowerCase()} item.`);
      lines.push('');
      lines.push(`### GET /${resource}/:id`);
      lines.push(`Get a specific ${lookupName(id).toLowerCase()} item.`);
      lines.push('');
      lines.push(`### PUT /${resource}/:id`);
      lines.push(`Update a ${lookupName(id).toLowerCase()} item.`);
      lines.push('');
      lines.push(`### DELETE /${resource}/:id`);
      lines.push(`Delete a ${lookupName(id).toLowerCase()} item.`);
      lines.push('');
    }
  }

  lines.push('---');
  lines.push(`*Generated by Blueprint Builder on ${today()}*`);
  return lines.join('\n');
}

function generateDatabaseDesign(bp: Blueprint): string {
  const name = bp.basics.name || 'Project';
  const lines: string[] = [];
  lines.push(`# Database Design — ${name}`);
  lines.push('');

  const dbs = bp.technology.database.map(lookupName);
  lines.push(`**Database:** ${dbs.length > 0 ? dbs.join(', ') : 'Not selected'}`);
  const orms = bp.technology.orm.map(lookupName);
  if (orms.length > 0) lines.push(`**ORM:** ${orms.join(', ')}`);
  lines.push('');

  // Core tables
  lines.push('## Core Tables');
  lines.push('');

  if (bp.features.selected.includes('authentication')) {
    lines.push('### users');
    lines.push('```sql');
    lines.push('CREATE TABLE users (');
    lines.push('  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),');
    lines.push('  email       VARCHAR(255) UNIQUE NOT NULL,');
    lines.push('  name        VARCHAR(255) NOT NULL,');
    lines.push('  password    VARCHAR(255) NOT NULL,');
    lines.push('  avatar_url  TEXT,');
    lines.push('  role        VARCHAR(50) DEFAULT \'user\',');
    lines.push('  created_at  TIMESTAMPTZ DEFAULT NOW(),');
    lines.push('  updated_at  TIMESTAMPTZ DEFAULT NOW()');
    lines.push(');');
    lines.push('```');
    lines.push('');
  }

  for (const id of bp.features.selected) {
    if (id === 'authentication') continue;
    const tableName = id.replace(/-/g, '_');
    lines.push(`### ${tableName}`);
    lines.push('```sql');
    
    if (id === 'dashboard') {
      lines.push(`CREATE TABLE dashboard_metrics (`);
      lines.push('  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),');
      lines.push('  metric_name VARCHAR(255) NOT NULL,');
      lines.push('  value       NUMERIC NOT NULL,');
      lines.push('  recorded_at TIMESTAMPTZ DEFAULT NOW()');
      lines.push(');');
    } else if (id === 'user-profiles') {
      lines.push(`CREATE TABLE user_profiles (`);
      lines.push('  user_id     UUID PRIMARY KEY REFERENCES users(id),');
      lines.push('  bio         TEXT,');
      lines.push('  website     VARCHAR(255),');
      lines.push('  preferences JSONB DEFAULT \'{}\',');
      lines.push('  updated_at  TIMESTAMPTZ DEFAULT NOW()');
      lines.push(');');
    } else if (id === 'payments') {
      lines.push(`CREATE TABLE subscriptions (`);
      lines.push('  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),');
      if (bp.features.selected.includes('authentication')) {
        lines.push('  user_id     UUID REFERENCES users(id),');
      }
      lines.push('  plan_id     VARCHAR(100) NOT NULL,');
      lines.push('  status      VARCHAR(50) NOT NULL,');
      lines.push('  current_period_end TIMESTAMPTZ,');
      lines.push('  created_at  TIMESTAMPTZ DEFAULT NOW()');
      lines.push(');');
    } else if (id === 'messaging') {
      lines.push(`CREATE TABLE messages (`);
      lines.push('  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),');
      lines.push('  conversation_id UUID NOT NULL,');
      if (bp.features.selected.includes('authentication')) {
        lines.push('  sender_id   UUID REFERENCES users(id),');
      }
      lines.push('  content     TEXT NOT NULL,');
      lines.push('  created_at  TIMESTAMPTZ DEFAULT NOW()');
      lines.push(');');
    } else {
      lines.push(`CREATE TABLE ${tableName} (`);
      lines.push('  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),');
      if (bp.features.selected.includes('authentication')) {
        lines.push('  user_id     UUID REFERENCES users(id),');
      }
      lines.push('  title       VARCHAR(255) NOT NULL,');
      lines.push('  data        JSONB DEFAULT \'{}\',');
      lines.push('  status      VARCHAR(50) DEFAULT \'active\',');
      lines.push('  created_at  TIMESTAMPTZ DEFAULT NOW(),');
      lines.push('  updated_at  TIMESTAMPTZ DEFAULT NOW()');
      lines.push(');');
    }
    lines.push('```');
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Generated by Blueprint Builder on ${today()}*`);
  return lines.join('\n');
}

function generateUserStories(bp: Blueprint): string {
  const name = bp.basics.name || 'Project';
  const lines: string[] = [];
  lines.push(`# User Stories — ${name}`);
  lines.push('');

  let storyNum = 1;
  for (const id of bp.features.selected) {
    const opt = featureOptions.find((o) => o.id === id);
    const featureName = lookupName(id);
    lines.push(`## US-${String(storyNum).padStart(3, '0')}: ${featureName}`);
    lines.push('');
    lines.push(`**As a** user`);
    lines.push(`**I want to** use the ${featureName.toLowerCase()} feature`);
    
    // Fix grammar by using description instead of raw bestUseCase
    let reason = opt?.description ? opt.description.toLowerCase() : `benefit from ${featureName.toLowerCase()}`;
    if (reason.endsWith('.')) reason = reason.slice(0, -1);
    lines.push(`**So that** I can achieve: ${reason}`);
    lines.push('');
    lines.push('### Acceptance Criteria');
    lines.push('');
    if (opt) {
      for (const adv of opt.advantages.slice(0, 3)) {
        lines.push(`- [ ] ${adv} is implemented and working`);
      }
    }
    lines.push(`- [ ] ${featureName} is accessible and responsive`);
    lines.push(`- [ ] Error states are handled gracefully`);
    lines.push(`- [ ] Unit tests cover core functionality`);
    lines.push('');
    lines.push(`**Priority:** ${opt && opt.popularity > 80 ? 'High' : opt && opt.popularity > 50 ? 'Medium' : 'Low'}`);
    lines.push(`**Difficulty:** ${opt?.difficulty ?? 'intermediate'}`);
    lines.push('');
    storyNum++;
  }

  if (bp.features.selected.length === 0) {
    lines.push('_No features selected. Add features to generate user stories._');
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Generated by Blueprint Builder on ${today()}*`);
  return lines.join('\n');
}

function generateArchitecture(bp: Blueprint): string {
  const name = bp.basics.name || 'Project';
  const lines: string[] = [];
  lines.push(`# Architecture Overview — ${name}`);
  lines.push('');

  lines.push('## System Architecture');
  lines.push('');
  lines.push('```');

  // ASCII art diagram
  const frontends = bp.technology.frontend.map(lookupName);
  const backends = bp.technology.backend.map(lookupName);
  const databases = bp.technology.database.map(lookupName);
  const hosting = bp.technology.hosting.map(lookupName);

  lines.push('┌─────────────────────────────────────────────────────────────┐');
  lines.push('│                        CLIENT TIER                         │');
  lines.push(`│  ${frontends.length > 0 ? frontends.join(' + ') : 'Frontend (not selected)'}`.padEnd(62) + '│');
  lines.push('├─────────────────────────────────────────────────────────────┤');
  lines.push('│                        SERVER TIER                         │');
  lines.push(`│  ${backends.length > 0 ? backends.join(' + ') : 'Backend (not selected)'}`.padEnd(62) + '│');
  lines.push('├─────────────────────────────────────────────────────────────┤');
  lines.push('│                         DATA TIER                          │');
  lines.push(`│  ${databases.length > 0 ? databases.join(' + ') : 'Database (not selected)'}`.padEnd(62) + '│');
  lines.push('├─────────────────────────────────────────────────────────────┤');
  lines.push('│                       INFRASTRUCTURE                       │');
  lines.push(`│  ${hosting.length > 0 ? hosting.join(' + ') : 'Hosting (not selected)'}`.padEnd(62) + '│');
  lines.push('└─────────────────────────────────────────────────────────────┘');
  lines.push('```');
  lines.push('');

  // Technology details
  lines.push('## Technology Stack Details');
  lines.push('');
  for (const [cat, names] of techByCategory(bp)) {
    lines.push(`### ${cat}`);
    for (const n of names) {
      const opt = allTechnologies.find((t) => t.name === n);
      lines.push(`- **${n}** — ${opt?.description ?? ''}`);
    }
    lines.push('');
  }

  // Integrations
  if (bp.integrations.selected.length > 0) {
    lines.push('## External Integrations');
    lines.push('');
    for (const id of bp.integrations.selected) {
      const opt = integrationOptions.find((o) => o.id === id);
      lines.push(`- **${lookupName(id)}** — ${opt?.description ?? ''}`);
    }
    lines.push('');
  }

  // Quality requirements
  const qual = qualityByCategory(bp);
  if (qual.length > 0) {
    lines.push('## Quality Attributes');
    lines.push('');
    for (const [cat, names] of qual) {
      lines.push(`### ${cat}`);
      for (const n of names) lines.push(`- ${n}`);
      lines.push('');
    }
  }

  lines.push('---');
  lines.push(`*Generated by Blueprint Builder on ${today()}*`);
  return lines.join('\n');
}

function generateTaskBreakdown(bp: Blueprint): string {
  const name = bp.basics.name || 'Project';
  const lines: string[] = [];
  lines.push(`# Task Breakdown — ${name}`);
  lines.push('');

  let phase = 1;

  // Phase 1: Setup
  lines.push(`## Phase ${phase}: Project Setup`);
  lines.push('');
  lines.push('- [ ] Initialize project repository');
  const tech = techByCategory(bp);
  for (const [cat, names] of tech) {
    lines.push(`- [ ] Set up ${cat}: ${names.join(', ')}`);
  }
  lines.push('- [ ] Configure development environment');
  lines.push('- [ ] Set up CI/CD pipeline');
  lines.push('');
  phase++;

  // Phase 2: Core features
  if (bp.features.selected.length > 0) {
    lines.push(`## Phase ${phase}: Core Features`);
    lines.push('');
    for (const id of bp.features.selected) {
      const opt = featureOptions.find((o) => o.id === id);
      lines.push(`### ${lookupName(id)}`);
      lines.push(`- [ ] Design ${lookupName(id).toLowerCase()} UI/UX`);
      lines.push(`- [ ] Implement backend logic`);
      lines.push(`- [ ] Build frontend components`);
      lines.push(`- [ ] Write tests`);
      if (opt) {
        lines.push(`- [ ] Estimated difficulty: ${opt.difficulty}`);
      }
      lines.push('');
    }
    phase++;
  }

  // Phase 3: Integrations
  if (bp.integrations.selected.length > 0) {
    lines.push(`## Phase ${phase}: Integrations`);
    lines.push('');
    for (const id of bp.integrations.selected) {
      lines.push(`- [ ] Integrate ${lookupName(id)}`);
      lines.push(`- [ ] Test ${lookupName(id)} integration`);
    }
    lines.push('');
    phase++;
  }

  // Phase 4: Quality
  const qual = qualityByCategory(bp);
  if (qual.length > 0) {
    lines.push(`## Phase ${phase}: Quality & Non-Functional`);
    lines.push('');
    for (const [cat, names] of qual) {
      lines.push(`### ${cat}`);
      for (const n of names) lines.push(`- [ ] Implement ${n}`);
      lines.push('');
    }
    phase++;
  }

  // Final phase
  lines.push(`## Phase ${phase}: Launch`);
  lines.push('');
  lines.push('- [ ] Final QA testing');
  lines.push('- [ ] Performance optimization');
  lines.push('- [ ] Security audit');
  lines.push('- [ ] Deploy to production');
  lines.push('- [ ] Monitor and iterate');
  lines.push('');

  lines.push('---');
  lines.push(`*Generated by Blueprint Builder on ${today()}*`);
  return lines.join('\n');
}

function generateTestingPlan(bp: Blueprint): string {
  const name = bp.basics.name || 'Project';
  const lines: string[] = [];
  lines.push(`# Testing Plan — ${name}`);
  lines.push('');

  lines.push('## Testing Strategy');
  lines.push('');
  lines.push('| Type | Coverage Target | Tools |');
  lines.push('|------|----------------|-------|');
  lines.push('| Unit Tests | 80%+ | Jest, Vitest |');
  lines.push('| Integration Tests | Critical paths | Supertest, MSW |');
  lines.push('| E2E Tests | User flows | Playwright, Cypress |');
  lines.push('| Performance Tests | Key endpoints | k6, Lighthouse |');
  lines.push('');

  lines.push('## Test Cases by Feature');
  lines.push('');
  for (const id of bp.features.selected) {
    const featureName = lookupName(id);
    lines.push(`### ${featureName}`);
    lines.push('');
    lines.push(`#### Unit Tests`);
    lines.push(`- [ ] ${featureName} core logic functions`);
    lines.push(`- [ ] Edge case handling`);
    lines.push(`- [ ] Error state validation`);
    lines.push('');
    lines.push(`#### Integration Tests`);
    lines.push(`- [ ] API endpoint for ${featureName.toLowerCase()}`);
    lines.push(`- [ ] Database operations`);
    lines.push('');
    lines.push(`#### E2E Tests`);
    lines.push(`- [ ] User flow for ${featureName.toLowerCase()}`);
    lines.push(`- [ ] Cross-browser compatibility`);
    lines.push('');
  }

  if (bp.features.selected.length === 0) {
    lines.push('_No features selected. Add features to generate test cases._');
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Generated by Blueprint Builder on ${today()}*`);
  return lines.join('\n');
}

function generateDeploymentGuide(bp: Blueprint): string {
  const name = bp.basics.name || 'Project';
  const lines: string[] = [];
  lines.push(`# Deployment Guide — ${name}`);
  lines.push('');

  const hosting = bp.technology.hosting.map(lookupName);
  lines.push(`**Target Platform:** ${hosting.length > 0 ? hosting.join(', ') : 'Not specified'}`);
  lines.push('');

  lines.push('## Prerequisites');
  lines.push('');
  lines.push('- Node.js 18+ installed');
  lines.push('- npm or yarn package manager');
  const dbs = bp.technology.database.map(lookupName);
  if (dbs.length > 0) lines.push(`- ${dbs.join(' / ')} instance`);
  lines.push('- Environment variables configured');
  lines.push('');

  lines.push('## Environment Variables');
  lines.push('');
  lines.push('```env');
  lines.push('NODE_ENV=production');
  lines.push('DATABASE_URL=your_database_url');
  if (bp.features.selected.includes('authentication')) {
    lines.push('JWT_SECRET=your_jwt_secret');
    lines.push('SESSION_SECRET=your_session_secret');
  }
  for (const id of bp.integrations.selected) {
    const key = id.toUpperCase().replace(/-/g, '_');
    lines.push(`${key}_API_KEY=your_${id}_api_key`);
  }
  lines.push('```');
  lines.push('');

  lines.push('## Build & Deploy');
  lines.push('');
  lines.push('```bash');
  lines.push('# Install dependencies');
  lines.push('npm ci');
  lines.push('');
  lines.push('# Build for production');
  lines.push('npm run build');
  lines.push('');
  lines.push('# Start production server');
  lines.push('npm start');
  lines.push('```');
  lines.push('');

  if (hosting.length > 0) {
    lines.push('## Platform-Specific Instructions');
    lines.push('');
    for (const h of hosting) {
      lines.push(`### ${h}`);
      lines.push(`Refer to the official ${h} deployment documentation for platform-specific setup.`);
      lines.push('');
    }
  }

  lines.push('## Post-Deployment Checklist');
  lines.push('');
  lines.push('- [ ] Verify all environment variables are set');
  lines.push('- [ ] Run database migrations');
  lines.push('- [ ] Test critical user flows');
  lines.push('- [ ] Enable monitoring and alerting');
  lines.push('- [ ] Configure SSL/TLS');
  lines.push('- [ ] Set up backup schedule');
  lines.push('');

  lines.push('---');
  lines.push(`*Generated by Blueprint Builder on ${today()}*`);
  return lines.join('\n');
}

function generateAIContext(bp: Blueprint): string {
  const name = bp.basics.name || 'Project';
  const lines: string[] = [];
  lines.push(`# AI Context File — ${name}`);
  lines.push('');
  lines.push('> This file provides context to AI coding assistants about the project structure, stack, and conventions.');
  lines.push('');

  lines.push('## Project Overview');
  lines.push('');
  lines.push(`- **Name:** ${name}`);
  lines.push(`- **Type:** ${fmt(bp.basics.projectType)}`);
  lines.push(`- **Industry:** ${bp.basics.industry || 'Not specified'}`);
  lines.push(`- **Business Model:** ${fmt(bp.basics.businessModel)}`);
  if (bp.basics.description) {
    lines.push(`- **Description:** ${bp.basics.description}`);
  }
  lines.push('');

  lines.push('## Technology Stack');
  lines.push('');
  for (const [cat, names] of techByCategory(bp)) {
    lines.push(`- **${cat}:** ${names.join(', ')}`);
  }
  lines.push('');

  lines.push('## Features');
  lines.push('');
  for (const id of bp.features.selected) {
    lines.push(`- ${lookupName(id)}`);
  }
  if (bp.features.selected.length === 0) lines.push('- None selected');
  lines.push('');

  lines.push('## Integrations');
  lines.push('');
  for (const id of bp.integrations.selected) {
    lines.push(`- ${lookupName(id)}`);
  }
  if (bp.integrations.selected.length === 0) lines.push('- None selected');
  lines.push('');

  lines.push('## Quality Requirements');
  lines.push('');
  for (const [cat, names] of qualityByCategory(bp)) {
    lines.push(`### ${cat}`);
    for (const n of names) lines.push(`- ${n}`);
    lines.push('');
  }

  lines.push('## Coding Conventions');
  lines.push('');
  lines.push('- Use TypeScript strict mode');
  lines.push('- Follow project structure conventions');
  lines.push('- Write tests for all new features');
  lines.push('- Use meaningful variable and function names');
  lines.push('- Handle errors gracefully with proper error types');
  lines.push('');

  lines.push('---');
  lines.push(`*Generated by Blueprint Builder on ${today()}*`);
  return lines.join('\n');
}

// ─── Acceptance Criteria Generator ───────────────────────────────────

function generateAcceptanceCriteria(bp: Blueprint): string {
  const name = bp.basics.name || 'Project';
  const lines: string[] = [];
  lines.push(`# Acceptance Criteria — ${name}`);
  lines.push('');
  lines.push(`**Date:** ${today()}`);
  lines.push(`**Status:** ${bp.status === 'complete' ? 'Final' : 'Draft'}`);
  lines.push('');
  lines.push('> This document defines testable acceptance criteria for every selected feature. Each criterion uses the **Given/When/Then** format for clarity.');
  lines.push('');

  if (bp.features.selected.length === 0) {
    lines.push('_No features selected. Add features to generate acceptance criteria._');
    return lines.join('\n');
  }

  const criteriaMap: Record<string, string[][]> = {
    'authentication': [
      ['a visitor is on the login page', 'they enter valid credentials and submit', 'they are redirected to the dashboard with an active session'],
      ['a visitor is on the registration page', 'they complete all required fields and submit', 'a new account is created and a verification email is sent'],
      ['an authenticated user clicks "Forgot Password"', 'they enter their email and submit', 'a password reset link is sent to their email'],
      ['a user session token expires', 'the user makes a request', 'they are redirected to the login page with a clear message'],
    ],
    'dashboard': [
      ['an authenticated user logs in', 'the dashboard loads', 'key metrics, activity feed, and quick actions are visible within 2 seconds'],
      ['new data is available', 'the user views the dashboard', 'metrics update to reflect the latest data without a full page reload'],
    ],
    'user-profiles': [
      ['an authenticated user visits their profile', 'the page loads', 'their avatar, name, email, and activity history are displayed'],
      ['a user edits their profile information', 'they save changes', 'the updated information is persisted and displayed immediately'],
    ],
    'notifications': [
      ['a relevant event occurs', 'the system generates a notification', 'the user sees an in-app notification badge within 5 seconds'],
      ['a user opens the notification panel', 'they view notifications', 'notifications are sorted by recency with unread items highlighted'],
      ['a user clicks a notification', 'the notification detail loads', 'they are navigated to the relevant content and the notification is marked as read'],
    ],
    'messaging': [
      ['two authenticated users exist', 'one sends a message to the other', 'the recipient sees the message in real-time without refreshing'],
      ['a user opens a conversation', 'the chat history loads', 'previous messages are displayed in chronological order'],
    ],
    'payments': [
      ['a user selects a plan or product', 'they enter valid payment details and submit', 'the payment is processed and a confirmation is displayed'],
      ['a payment fails', 'the system receives an error from the payment provider', 'the user sees a clear error message with retry instructions'],
      ['a subscription renewal is due', 'the billing cycle completes', 'the payment is automatically processed and the user is notified'],
    ],
    'ai-features': [
      ['a user triggers an AI action', 'the system processes the request', 'a response is generated within 10 seconds with a loading indicator shown during processing'],
      ['the AI service is unavailable', 'a user triggers an AI action', 'a graceful fallback message is displayed without breaking the UI'],
    ],
    'file-uploads': [
      ['a user selects a file to upload', 'the file is within size and type limits', 'the file is uploaded with a progress indicator and stored successfully'],
      ['a user selects a file exceeding the size limit', 'they attempt to upload', 'a clear error message is shown before upload begins'],
    ],
    'analytics': [
      ['a user performs a tracked action', 'the event is triggered', 'the analytics event is recorded with correct properties'],
      ['an admin views the analytics dashboard', 'the page loads', 'aggregated metrics for the selected time period are displayed'],
    ],
    'admin-panel': [
      ['an admin user logs in', 'they access the admin panel', 'they can view, search, and manage all users and content'],
      ['an admin performs a destructive action', 'they confirm the action', 'a confirmation dialog is shown before execution and an audit log entry is created'],
    ],
    'search': [
      ['a user types a search query', 'results begin appearing', 'relevant results are shown within 300ms of the last keystroke'],
      ['a user searches for a non-existent term', 'the search completes', 'a "no results" message with suggestions is displayed'],
    ],
    'settings': [
      ['a user opens settings', 'the page loads', 'all current preferences are displayed with their current values'],
      ['a user changes a setting and saves', 'the save completes', 'the new value is persisted and reflected immediately across the app'],
    ],
  };

  for (const featureId of bp.features.selected) {
    const opt = featureOptions.find((o) => o.id === featureId);
    const featureName = opt?.name ?? lookupName(featureId);
    const featureIcon = opt?.icon ?? '•';

    lines.push(`## ${featureIcon} ${featureName}`);
    lines.push('');

    const criteria = criteriaMap[featureId];
    if (criteria && criteria.length > 0) {
      for (let i = 0; i < criteria.length; i++) {
        const [given, when, then] = criteria[i];
        lines.push(`### AC-${featureId.toUpperCase().replace(/-/g, '')}-${i + 1}`);
        lines.push('');
        lines.push(`- **Given** ${given}`);
        lines.push(`- **When** ${when}`);
        lines.push(`- **Then** ${then}`);
        lines.push('');
      }
    } else {
      // Generic acceptance criteria for features without specific mappings
      lines.push(`### AC-${featureId.toUpperCase().replace(/-/g, '')}-1`);
      lines.push('');
      lines.push(`- **Given** the ${featureName} feature is enabled`);
      lines.push(`- **When** a user accesses the ${featureName} functionality`);
      lines.push(`- **Then** the feature works as described: "${opt?.description ?? 'Feature is functional'}" without errors`);
      lines.push('');
      lines.push(`### AC-${featureId.toUpperCase().replace(/-/g, '')}-2`);
      lines.push('');
      lines.push(`- **Given** the ${featureName} feature encounters an error`);
      lines.push(`- **When** the error is handled`);
      lines.push(`- **Then** the user sees a meaningful error message and the application remains stable`);
      lines.push('');
    }
  }

  lines.push('---');
  lines.push(`*Generated by Blueprint Builder on ${today()}*`);
  return lines.join('\n');
}

// ─── Document Registry ───────────────────────────────────────────────

export const documentTypes: DocumentType[] = [
  { id: 'prd', title: 'Product Requirements (PRD)', icon: '📋', description: 'Complete product requirements with features, stack, and quality specs.', generate: generatePRD },
  { id: 'readme', title: 'README', icon: '📖', description: 'Project README with badges, setup instructions, and tech stack.', generate: generateREADME },
  { id: 'api-spec', title: 'API Specification', icon: '🔌', description: 'RESTful API endpoints based on selected features.', generate: generateAPISpec },
  { id: 'database', title: 'Database Design', icon: '🗄️', description: 'Database schema with tables derived from features.', generate: generateDatabaseDesign },
  { id: 'user-stories', title: 'User Stories', icon: '👤', description: 'User stories with acceptance criteria for each feature.', generate: generateUserStories },
  { id: 'acceptance-criteria', title: 'Acceptance Criteria', icon: '✅', description: 'Testable acceptance criteria in Given/When/Then format.', generate: generateAcceptanceCriteria },
  { id: 'architecture', title: 'Architecture Overview', icon: '🏗️', description: 'System architecture diagram and technology details.', generate: generateArchitecture },
  { id: 'tasks', title: 'Task Breakdown', icon: '📝', description: 'Development task checklist organized by phase.', generate: generateTaskBreakdown },
  { id: 'testing', title: 'Testing Plan', icon: '🧪', description: 'Testing strategy with test cases per feature.', generate: generateTestingPlan },
  { id: 'deployment', title: 'Deployment Guide', icon: '🚀', description: 'Deployment instructions with env vars and checklists.', generate: generateDeploymentGuide },
  { id: 'ai-context', title: 'AI Context File', icon: '🤖', description: 'Context file for AI coding assistants.', generate: generateAIContext },
];

export function generateDocuments(
  blueprint: Blueprint,
  selectedIds: string[]
): GeneratedDocument[] {
  return selectedIds
    .map((id) => documentTypes.find((d) => d.id === id))
    .filter((d): d is DocumentType => d !== undefined)
    .map((doc) => ({
      id: doc.id,
      title: doc.title,
      icon: doc.icon,
      description: doc.description,
      content: doc.generate(blueprint),
    }));
}
