import { Blueprint } from '@/types/blueprint';
import { allTechnologies } from '@/data/options/technologies';
import { featureOptions } from '@/data/options/features';
import { integrationOptions } from '@/data/options/integrations';
import { qualityOptions } from '@/data/options/quality';

// ─── Helpers ─────────────────────────────────────────────────────────

function fmt(val: string | null): string {
  if (!val) return 'N/A';
  return val.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

function lookupName(id: string): string {
  const opt =
    allTechnologies.find((o) => o.id === id) ??
    featureOptions.find((o) => o.id === id) ??
    integrationOptions.find((o) => o.id === id) ??
    Object.values(qualityOptions).flat().find((o) => o.id === id);
  return opt?.name ?? fmt(id);
}

function techByCategory(bp: Blueprint): [string, string[]][] {
  return Object.entries(bp.technology)
    .filter(([, ids]) => ids && Array.isArray(ids) && ids.length > 0)
    .map(([cat, ids]) => [fmt(cat), ids.map(lookupName).filter(Boolean)] as [string, string[]])
    .filter(([, names]) => names.length > 0);
}

function qualityByCategory(bp: Blueprint): [string, string[]][] {
  return Object.entries(bp.quality)
    .filter(([, ids]) => ids.length > 0)
    .map(([cat, ids]) => [fmt(cat), ids.map(lookupName)]);
}

function today(): string {
  return new Date().toISOString().split('T')[0];
}

// ─── Document Metadata ──────────────────────────────────────────────

export interface GeneratedDocument {
  id: string;
  title: string;
  icon: string;
  description: string;
  content: string;
}

export interface DocumentType {
  id: string;
  title: string;
  icon: string;
  description: string;
  generate: (bp: Blueprint) => string;
}

// ─── Generators ──────────────────────────────────────────────────────

function generatePRD(bp: Blueprint): string {
  const name = bp.basics.name || 'Untitled Project';
  const tech = techByCategory(bp);
  const qual = qualityByCategory(bp);
  
  return `# Product Requirements Document (PRD)
## ${name}

**Date:** ${today()}
**Status:** ${bp.status === 'complete' ? 'Final' : 'Draft'}

## 1. Overview

**Project Name:** ${name}
**Project Type:** ${fmt(bp.basics.projectType)}
**Industry:** ${bp.basics.industry || 'Not specified'}
**Target Audience:** ${bp.basics.targetAudience || 'Not specified'}
**Business Model:** ${fmt(bp.basics.businessModel)}
${bp.basics.description ? `\n### Description\n\n${bp.basics.description}\n` : ''}
## 2. Target Platforms

${bp.basics.targetPlatforms.length > 0 ? bp.basics.targetPlatforms.map(p => `- ${fmt(p)}`).join('\n') : '_No platforms selected._'}

## 3. Technology Stack

${tech.length > 0 ? `| Layer | Technologies |\n|-------|-------------|\n${tech.map(([cat, names]) => `| **${cat}** | ${names.join(', ')} |`).join('\n')}` : '_No technologies selected._'}

## 4. Features

${bp.features.selected.length > 0 ? bp.features.selected.map(id => {
  const opt = featureOptions.find((o) => o.id === id);
  return `### ${opt?.icon ?? '•'} ${lookupName(id)}\n${opt?.description ?? ''}\n`;
}).join('\n') : '_No features selected._\n'}
## 5. Integrations

${bp.integrations.selected.length > 0 ? bp.integrations.selected.map(id => {
  const opt = integrationOptions.find((o) => o.id === id);
  return `- **${lookupName(id)}** — ${opt?.description ?? ''}`;
}).join('\n') : '_No integrations selected._'}

## 6. Quality & Non-Functional Requirements

${qual.length > 0 ? qual.map(([cat, names]) => `### ${cat}\n${names.map(n => `- ${n}`).join('\n')}\n`).join('\n') : '_No quality configurations set._\n'}
---
*Generated by Blueprint Builder on ${today()}*`;
}

function generateREADME(bp: Blueprint): string {
  const name = bp.basics.name || 'Project';
  const tech = techByCategory(bp);
  
  return `# ${name}

${bp.basics.description ? `> ${bp.basics.description}\n` : ''}
![Type](https://img.shields.io/badge/type-${encodeURIComponent(fmt(bp.basics.projectType))}-6366f1)
![Status](https://img.shields.io/badge/status-${bp.status}-10b981)

## Tech Stack

${tech.map(([cat, names]) => `- **${cat}:** ${names.join(', ')}`).join('\n')}

## Features

${bp.features.selected.length > 0 ? bp.features.selected.map(id => `- ${lookupName(id)}`).join('\n') : '_None selected._'}

${bp.integrations.selected.length > 0 ? `\n## Integrations\n\n${bp.integrations.selected.map(id => `- ${lookupName(id)}`).join('\n')}\n` : ''}
## Getting Started

\`\`\`bash
# Install dependencies
npm install

# Start development server
npm run dev
\`\`\`

## License

MIT

---
*Generated by Blueprint Builder on ${today()}*`;
}

function generateAPISpec(bp: Blueprint): string {
  const name = bp.basics.name || 'Project';
  let content = `# API Specification — ${name}\n\n**Base URL:** \`https://api.${name.toLowerCase().replace(/[^a-z0-9]/g, '')}.com/v1\`\n\n`;
  
  if (bp.features.selected.includes('authentication')) {
    content += `## Authentication\n
### POST /auth/register
Create a new user account.
\`\`\`json
{ "email": "string", "password": "string", "name": "string" }
\`\`\`

### POST /auth/login
Authenticate and receive a token.
\`\`\`json
{ "email": "string", "password": "string" }
\`\`\`

### POST /auth/logout
Invalidate the current session.

`;
  }

  for (const id of bp.features.selected) {
    if (id === 'authentication') continue;
    const resource = id.replace(/-/g, '_');
    content += `## ${lookupName(id)}\n\n`;
    
    if (id === 'dashboard') {
      content += `### GET /dashboard/metrics\nRetrieve aggregated metrics for the dashboard view.\n\n### GET /dashboard/activity\nGet recent activity feed for the dashboard.\n\n`;
    } else if (id === 'user-profiles') {
      content += `### GET /users/:id/profile\nGet a specific user's public profile data.\n\n### PUT /users/me/profile\nUpdate the authenticated user's profile.\n\n`;
    } else if (id === 'payments') {
      content += `### POST /payments/checkout\nCreate a new checkout session.\n\n### GET /payments/subscriptions\nList active subscriptions for the user.\n\n`;
    } else if (id === 'messaging') {
      content += `### GET /conversations\nList all active conversations for the user.\n\n### POST /conversations/:id/messages\nSend a new message in a conversation.\n\n`;
    } else if (id === 'file-uploads') {
      content += `### POST /uploads/presigned-url\nGet a pre-signed URL for direct cloud upload.\n\n`;
    } else if (id === 'search') {
      content += `### GET /search\nPerform a full-text search query across resources.\n\n`;
    } else {
      content += `### GET /${resource}\nList all ${lookupName(id).toLowerCase()} items.\n
### POST /${resource}\nCreate a new ${lookupName(id).toLowerCase()} item.\n
### GET /${resource}/:id\nGet a specific ${lookupName(id).toLowerCase()} item.\n
### PUT /${resource}/:id\nUpdate a ${lookupName(id).toLowerCase()} item.\n
### DELETE /${resource}/:id\nDelete a ${lookupName(id).toLowerCase()} item.\n\n`;
    }
  }

  return content + `---\n*Generated by Blueprint Builder on ${today()}*`;
}

function generateDatabaseDesign(bp: Blueprint): string {
  const name = bp.basics.name || 'Project';
  const dbs = bp.technology.database.map(lookupName);
  const orms = bp.technology.orm.map(lookupName);
  
  let content = `# Database Design — ${name}\n\n**Database:** ${dbs.length > 0 ? dbs.join(', ') : 'Not selected'}\n${orms.length > 0 ? `**ORM:** ${orms.join(', ')}\n` : ''}\n## Core Tables\n\n`;

  if (bp.features.selected.includes('authentication')) {
    content += `### users
\`\`\`sql
CREATE TABLE users (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email       VARCHAR(255) UNIQUE NOT NULL,
  name        VARCHAR(255) NOT NULL,
  password    VARCHAR(255) NOT NULL,
  avatar_url  TEXT,
  role        VARCHAR(50) DEFAULT 'user',
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);
\`\`\`\n\n`;
  }

  for (const id of bp.features.selected) {
    if (id === 'authentication') continue;
    const tableName = id.replace(/-/g, '_');
    content += `### ${tableName}\n\`\`\`sql\n`;
    
    if (id === 'dashboard') {
      content += `CREATE TABLE dashboard_metrics (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  metric_name VARCHAR(255) NOT NULL,
  value       NUMERIC NOT NULL,
  recorded_at TIMESTAMPTZ DEFAULT NOW()
);`;
    } else if (id === 'user-profiles') {
      content += `CREATE TABLE user_profiles (
  user_id     UUID PRIMARY KEY REFERENCES users(id),
  bio         TEXT,
  website     VARCHAR(255),
  preferences JSONB DEFAULT '{}',
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);`;
    } else if (id === 'payments') {
      content += `CREATE TABLE subscriptions (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
${bp.features.selected.includes('authentication') ? '  user_id     UUID REFERENCES users(id),\n' : ''}  plan_id     VARCHAR(100) NOT NULL,
  status      VARCHAR(50) NOT NULL,
  current_period_end TIMESTAMPTZ,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);`;
    } else if (id === 'messaging') {
      content += `CREATE TABLE messages (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id UUID NOT NULL,
${bp.features.selected.includes('authentication') ? '  sender_id   UUID REFERENCES users(id),\n' : ''}  content     TEXT NOT NULL,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);`;
    } else {
      content += `CREATE TABLE ${tableName} (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
${bp.features.selected.includes('authentication') ? '  user_id     UUID REFERENCES users(id),\n' : ''}  title       VARCHAR(255) NOT NULL,
  data        JSONB DEFAULT '{}',
  status      VARCHAR(50) DEFAULT 'active',
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);`;
    }
    content += `\n\`\`\`\n\n`;
  }

  return content + `---\n*Generated by Blueprint Builder on ${today()}*`;
}

function generateUserStories(bp: Blueprint): string {
  const name = bp.basics.name || 'Project';
  if (bp.features.selected.length === 0) return `# User Stories — ${name}\n\n_No features selected. Add features to generate user stories._\n\n---\n*Generated by Blueprint Builder on ${today()}*`;
  
  const stories = bp.features.selected.map((id, index) => {
    const opt = featureOptions.find((o) => o.id === id);
    const featureName = lookupName(id);
    let reason = opt?.description ? opt.description.toLowerCase() : `benefit from ${featureName.toLowerCase()}`;
    if (reason.endsWith('.')) reason = reason.slice(0, -1);
    
    return `## US-${String(index + 1).padStart(3, '0')}: ${featureName}\n
**As a** user
**I want to** use the ${featureName.toLowerCase()} feature
**So that** I can achieve: ${reason}\n
### Acceptance Criteria\n
${opt?.advantages.slice(0, 3).map(adv => `- [ ] ${adv} is implemented and working`).join('\n') ?? ''}
- [ ] ${featureName} is accessible and responsive
- [ ] Error states are handled gracefully
- [ ] Unit tests cover core functionality\n
**Priority:** ${opt && opt.popularity > 80 ? 'High' : opt && opt.popularity > 50 ? 'Medium' : 'Low'}
**Difficulty:** ${opt?.difficulty ?? 'intermediate'}\n`;
  });

  return `# User Stories — ${name}\n\n${stories.join('\n')}\n---\n*Generated by Blueprint Builder on ${today()}*`;
}

function generateArchitecture(bp: Blueprint): string {
  const name = bp.basics.name || 'Project';
  const frontends = bp.technology.frontend.map(lookupName);
  const backends = bp.technology.backend.map(lookupName);
  const databases = bp.technology.database.map(lookupName);
  const hosting = bp.technology.hosting.map(lookupName);
  
  return `# Architecture Overview — ${name}\n
## System Architecture\n
\`\`\`
┌─────────────────────────────────────────────────────────────┐
│                        CLIENT TIER                         │
│  ${(frontends.length > 0 ? frontends.join(' + ') : 'Frontend (not selected)').padEnd(62)}│
├─────────────────────────────────────────────────────────────┤
│                        SERVER TIER                         │
│  ${(backends.length > 0 ? backends.join(' + ') : 'Backend (not selected)').padEnd(62)}│
├─────────────────────────────────────────────────────────────┤
│                         DATA TIER                          │
│  ${(databases.length > 0 ? databases.join(' + ') : 'Database (not selected)').padEnd(62)}│
├─────────────────────────────────────────────────────────────┤
│                       INFRASTRUCTURE                       │
│  ${(hosting.length > 0 ? hosting.join(' + ') : 'Hosting (not selected)').padEnd(62)}│
└─────────────────────────────────────────────────────────────┘
\`\`\`\n
## Technology Stack Details\n
${techByCategory(bp).map(([cat, names]) => `### ${cat}\n${names.map(n => `- **${n}** — ${allTechnologies.find(t => t.name === n)?.description ?? ''}`).join('\n')}\n`).join('\n')}
${bp.integrations.selected.length > 0 ? `## External Integrations\n\n${bp.integrations.selected.map(id => `- **${lookupName(id)}** — ${integrationOptions.find(o => o.id === id)?.description ?? ''}`).join('\n')}\n` : ''}
${qualityByCategory(bp).length > 0 ? `## Quality Attributes\n\n${qualityByCategory(bp).map(([cat, names]) => `### ${cat}\n${names.map(n => `- ${n}`).join('\n')}\n`).join('\n')}` : ''}
---
*Generated by Blueprint Builder on ${today()}*`;
}

function generateTaskBreakdown(bp: Blueprint): string {
  const name = bp.basics.name || 'Project';
  let phase = 1;
  let content = `# Task Breakdown — ${name}\n\n## Phase ${phase++}: Project Setup\n\n- [ ] Initialize project repository\n${techByCategory(bp).map(([cat, names]) => `- [ ] Set up ${cat}: ${names.join(', ')}`).join('\n')}\n- [ ] Configure development environment\n- [ ] Set up CI/CD pipeline\n\n`;

  if (bp.features.selected.length > 0) {
    content += `## Phase ${phase++}: Core Features\n\n${bp.features.selected.map(id => {
      const opt = featureOptions.find((o) => o.id === id);
      return `### ${lookupName(id)}\n- [ ] Design ${lookupName(id).toLowerCase()} UI/UX\n- [ ] Implement backend logic\n- [ ] Build frontend components\n- [ ] Write tests\n${opt ? `- [ ] Estimated difficulty: ${opt.difficulty}\n` : ''}`;
    }).join('\n')}\n`;
  }

  if (bp.integrations.selected.length > 0) {
    content += `## Phase ${phase++}: Integrations\n\n${bp.integrations.selected.map(id => `- [ ] Integrate ${lookupName(id)}\n- [ ] Test ${lookupName(id)} integration`).join('\n')}\n\n`;
  }

  const qual = qualityByCategory(bp);
  if (qual.length > 0) {
    content += `## Phase ${phase++}: Quality & Non-Functional\n\n${qual.map(([cat, names]) => `### ${cat}\n${names.map(n => `- [ ] Implement ${n}`).join('\n')}\n`).join('\n')}\n`;
  }

  content += `## Phase ${phase}: Launch\n\n- [ ] Final QA testing\n- [ ] Performance optimization\n- [ ] Security audit\n- [ ] Deploy to production\n- [ ] Monitor and iterate\n\n---\n*Generated by Blueprint Builder on ${today()}*`;
  return content;
}

function generateTestingPlan(bp: Blueprint): string {
  const name = bp.basics.name || 'Project';
  return `# Testing Plan — ${name}\n
## Testing Strategy\n
| Type | Coverage Target | Tools |
|------|----------------|-------|
| Unit Tests | 80%+ | Jest, Vitest |
| Integration Tests | Critical paths | Supertest, MSW |
| E2E Tests | User flows | Playwright, Cypress |
| Performance Tests | Key endpoints | k6, Lighthouse |\n
## Test Cases by Feature\n
${bp.features.selected.length > 0 ? bp.features.selected.map(id => {
  const featureName = lookupName(id);
  return `### ${featureName}\n
#### Unit Tests
- [ ] ${featureName} core logic functions
- [ ] Edge case handling
- [ ] Error state validation\n
#### Integration Tests
- [ ] API endpoint for ${featureName.toLowerCase()}
- [ ] Database operations\n
#### E2E Tests
- [ ] User flow for ${featureName.toLowerCase()}
- [ ] Cross-browser compatibility\n`;
}).join('\n') : '_No features selected. Add features to generate test cases._\n'}
---
*Generated by Blueprint Builder on ${today()}*`;
}

function generateDeploymentGuide(bp: Blueprint): string {
  const name = bp.basics.name || 'Project';
  const hosting = bp.technology.hosting.map(lookupName);
  const dbs = bp.technology.database.map(lookupName);
  
  return `# Deployment Guide — ${name}\n
**Target Platform:** ${hosting.length > 0 ? hosting.join(', ') : 'Not specified'}\n
## Prerequisites\n
- Node.js 18+ installed
- npm or yarn package manager
${dbs.length > 0 ? `- ${dbs.join(' / ')} instance\n` : ''}- Environment variables configured\n
## Environment Variables\n
\`\`\`env
NODE_ENV=production
DATABASE_URL=your_database_url
${bp.features.selected.includes('authentication') ? 'JWT_SECRET=your_jwt_secret\nSESSION_SECRET=your_session_secret\n' : ''}${bp.integrations.selected.map(id => `${id.toUpperCase().replace(/-/g, '_')}_API_KEY=your_${id}_api_key`).join('\n')}
\`\`\`\n
## Build & Deploy\n
\`\`\`bash
# Install dependencies
npm ci

# Build for production
npm run build

# Start production server
npm start
\`\`\`\n
${hosting.length > 0 ? `## Platform-Specific Instructions\n\n${hosting.map(h => `### ${h}\nRefer to the official ${h} deployment documentation for platform-specific setup.\n`).join('\n')}\n` : ''}## Post-Deployment Checklist\n
- [ ] Verify all environment variables are set
- [ ] Run database migrations
- [ ] Test critical user flows
- [ ] Enable monitoring and alerting
- [ ] Configure SSL/TLS
- [ ] Set up backup schedule\n
---
*Generated by Blueprint Builder on ${today()}*`;
}

function generateAIContext(bp: Blueprint): string {
  const name = bp.basics.name || 'Project';
  
  return `# AI Context File — ${name}\n
> This file provides context to AI coding assistants about the project structure, stack, and conventions.\n
## Project Overview\n
- **Name:** ${name}
- **Type:** ${fmt(bp.basics.projectType)}
- **Industry:** ${bp.basics.industry || 'Not specified'}
- **Business Model:** ${fmt(bp.basics.businessModel)}
${bp.basics.description ? `- **Description:** ${bp.basics.description}` : ''}\n
## Technology Stack\n
${techByCategory(bp).map(([cat, names]) => `- **${cat}:** ${names.join(', ')}`).join('\n')}\n
## Features\n
${bp.features.selected.length > 0 ? bp.features.selected.map(id => `- ${lookupName(id)}`).join('\n') : '- None selected'}\n
## Integrations\n
${bp.integrations.selected.length > 0 ? bp.integrations.selected.map(id => `- ${lookupName(id)}`).join('\n') : '- None selected'}\n
## Quality Requirements\n
${qualityByCategory(bp).map(([cat, names]) => `### ${cat}\n${names.map(n => `- ${n}`).join('\n')}\n`).join('\n')}
## Coding Conventions\n
- Use TypeScript strict mode
- Follow project structure conventions
- Write tests for all new features
- Use meaningful variable and function names
- Handle errors gracefully with proper error types\n
---
*Generated by Blueprint Builder on ${today()}*`;
}

function generateAcceptanceCriteria(bp: Blueprint): string {
  const name = bp.basics.name || 'Project';
  if (bp.features.selected.length === 0) return `# Acceptance Criteria — ${name}\n\n**Date:** ${today()}\n**Status:** ${bp.status === 'complete' ? 'Final' : 'Draft'}\n\n> This document defines testable acceptance criteria for every selected feature. Each criterion uses the **Given/When/Then** format for clarity.\n\n_No features selected. Add features to generate acceptance criteria._\n\n---\n*Generated by Blueprint Builder on ${today()}*`;

  const criteriaMap: Record<string, string[][]> = {
    'authentication': [
      ['a visitor is on the login page', 'they enter valid credentials and submit', 'they are redirected to the dashboard with an active session'],
      ['a visitor is on the registration page', 'they complete all required fields and submit', 'a new account is created and a verification email is sent'],
      ['an authenticated user clicks "Forgot Password"', 'they enter their email and submit', 'a password reset link is sent to their email'],
      ['a user session token expires', 'the user makes a request', 'they are redirected to the login page with a clear message'],
    ],
    'dashboard': [
      ['an authenticated user logs in', 'the dashboard loads', 'key metrics, activity feed, and quick actions are visible within 2 seconds'],
      ['new data is available', 'the user views the dashboard', 'metrics update to reflect the latest data without a full page reload'],
    ],
    'user-profiles': [
      ['an authenticated user visits their profile', 'the page loads', 'their avatar, name, email, and activity history are displayed'],
      ['a user edits their profile information', 'they save changes', 'the updated information is persisted and displayed immediately'],
    ],
    'notifications': [
      ['a relevant event occurs', 'the system generates a notification', 'the user sees an in-app notification badge within 5 seconds'],
      ['a user opens the notification panel', 'they view notifications', 'notifications are sorted by recency with unread items highlighted'],
      ['a user clicks a notification', 'the notification detail loads', 'they are navigated to the relevant content and the notification is marked as read'],
    ],
    'messaging': [
      ['two authenticated users exist', 'one sends a message to the other', 'the recipient sees the message in real-time without refreshing'],
      ['a user opens a conversation', 'the chat history loads', 'previous messages are displayed in chronological order'],
    ],
    'payments': [
      ['a user selects a plan or product', 'they enter valid payment details and submit', 'the payment is processed and a confirmation is displayed'],
      ['a payment fails', 'the system receives an error from the payment provider', 'the user sees a clear error message with retry instructions'],
      ['a subscription renewal is due', 'the billing cycle completes', 'the payment is automatically processed and the user is notified'],
    ],
    'ai-features': [
      ['a user triggers an AI action', 'the system processes the request', 'a response is generated within 10 seconds with a loading indicator shown during processing'],
      ['the AI service is unavailable', 'a user triggers an AI action', 'a graceful fallback message is displayed without breaking the UI'],
    ],
    'file-uploads': [
      ['a user selects a file to upload', 'the file is within size and type limits', 'the file is uploaded with a progress indicator and stored successfully'],
      ['a user selects a file exceeding the size limit', 'they attempt to upload', 'a clear error message is shown before upload begins'],
    ],
    'analytics': [
      ['a user performs a tracked action', 'the event is triggered', 'the analytics event is recorded with correct properties'],
      ['an admin views the analytics dashboard', 'the page loads', 'aggregated metrics for the selected time period are displayed'],
    ],
    'admin-panel': [
      ['an admin user logs in', 'they access the admin panel', 'they can view, search, and manage all users and content'],
      ['an admin performs a destructive action', 'they confirm the action', 'a confirmation dialog is shown before execution and an audit log entry is created'],
    ],
    'search': [
      ['a user types a search query', 'results begin appearing', 'relevant results are shown within 300ms of the last keystroke'],
      ['a user searches for a non-existent term', 'the search completes', 'a "no results" message with suggestions is displayed'],
    ],
    'settings': [
      ['a user opens settings', 'the page loads', 'all current preferences are displayed with their current values'],
      ['a user changes a setting and saves', 'the save completes', 'the new value is persisted and reflected immediately across the app'],
    ],
  };

  const featureBlocks = bp.features.selected.map(featureId => {
    const opt = featureOptions.find((o) => o.id === featureId);
    const featureName = opt?.name ?? lookupName(featureId);
    const featureIcon = opt?.icon ?? '•';
    
    let content = `## ${featureIcon} ${featureName}\n\n`;
    const criteria = criteriaMap[featureId];
    
    if (criteria && criteria.length > 0) {
      content += criteria.map(([given, when, then], i) => `### AC-${featureId.toUpperCase().replace(/-/g, '')}-${i + 1}\n\n- **Given** ${given}\n- **When** ${when}\n- **Then** ${then}\n`).join('\n');
    } else {
      content += `### AC-${featureId.toUpperCase().replace(/-/g, '')}-1\n\n- **Given** the ${featureName} feature is enabled\n- **When** a user accesses the ${featureName} functionality\n- **Then** the feature works as described: "${opt?.description ?? 'Feature is functional'}" without errors\n\n### AC-${featureId.toUpperCase().replace(/-/g, '')}-2\n\n- **Given** the ${featureName} feature encounters an error\n- **When** the error is handled\n- **Then** the user sees a meaningful error message and the application remains stable\n\n`;
    }
    return content;
  }).join('\n');

  return `# Acceptance Criteria — ${name}\n\n**Date:** ${today()}\n**Status:** ${bp.status === 'complete' ? 'Final' : 'Draft'}\n\n> This document defines testable acceptance criteria for every selected feature. Each criterion uses the **Given/When/Then** format for clarity.\n\n${featureBlocks}\n---\n*Generated by Blueprint Builder on ${today()}*`;
}

// ─── Document Registry ───────────────────────────────────────────────

export const documentTypes: DocumentType[] = [
  { id: 'prd', title: 'Product Requirements (PRD)', icon: '📋', description: 'Complete product requirements with features, stack, and quality specs.', generate: generatePRD },
  { id: 'readme', title: 'README', icon: '📖', description: 'Project README with badges, setup instructions, and tech stack.', generate: generateREADME },
  { id: 'api-spec', title: 'API Specification', icon: '🔌', description: 'RESTful API endpoints based on selected features.', generate: generateAPISpec },
  { id: 'database', title: 'Database Design', icon: '🗄️', description: 'Database schema with tables derived from features.', generate: generateDatabaseDesign },
  { id: 'user-stories', title: 'User Stories', icon: '👤', description: 'User stories with acceptance criteria for each feature.', generate: generateUserStories },
  { id: 'acceptance-criteria', title: 'Acceptance Criteria', icon: '✅', description: 'Testable acceptance criteria in Given/When/Then format.', generate: generateAcceptanceCriteria },
  { id: 'architecture', title: 'Architecture Overview', icon: '🏗️', description: 'System architecture diagram and technology details.', generate: generateArchitecture },
  { id: 'tasks', title: 'Task Breakdown', icon: '📝', description: 'Development task checklist organized by phase.', generate: generateTaskBreakdown },
  { id: 'testing', title: 'Testing Plan', icon: '🧪', description: 'Testing strategy with test cases per feature.', generate: generateTestingPlan },
  { id: 'deployment', title: 'Deployment Guide', icon: '🚀', description: 'Deployment instructions with env vars and checklists.', generate: generateDeploymentGuide },
  { id: 'ai-context', title: 'AI Context File', icon: '🤖', description: 'Context file for AI coding assistants.', generate: generateAIContext },
];

export function generateDocuments(
  blueprint: Blueprint,
  selectedIds: string[]
): GeneratedDocument[] {
  return selectedIds
    .map((id) => documentTypes.find((d) => d.id === id))
    .filter((d): d is DocumentType => d !== undefined)
    .map((doc) => ({
      id: doc.id,
      title: doc.title,
      icon: doc.icon,
      description: doc.description,
      content: doc.generate(blueprint),
    }));
}
